# Generic Errors
NOT_AUTHORISED = "NOT_AUTHORISED"
TOKEN_ID_ALREADY_EXISTS = "TOKEN_ID_ALREADY_EXISTS"
INVALID_VIEW = "INVALID_VIEW"

# Game
VICTIM_ALREADY_DEAD = "VICTIM_ALREADY_DEAD"

# Locker
ZERO_AMOUNT_BEING_LOCKED = "ZERO_AMOUNT_BEING_LOCKED"
